# -*- coding: utf-8 -*-
"""build_learn.py — build the Learning-section data for the SE quiz site.

Reads a Hebrew course summary (markdown, tools/se_summary.md), splits it into
sections by '## ' headings, renders each to HTML, optionally appends curated
figures, and emits:

    ../learn.js   ->  window.LEARN = [{id, title, html}, ...]

Mirrors the DS questions/learn pipeline: the site stays 100% static and offline
(no runtime markdown parser, no CDN). Run:  python tools/build_learn.py
"""
import os, re, json, html, datetime, io, sys
import markdown
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8")

HERE    = os.path.dirname(os.path.abspath(__file__))
ROOT    = os.path.dirname(HERE)
SUMMARY = os.path.join(HERE, "se_summary.md")
OUT_IMG = os.path.join(ROOT, "images")
OUT_JS  = os.path.join(ROOT, "learn.js")

# section-id -> [(image filename already in images/, Hebrew caption), ...]
# Empty for now (text-first learn mode); add entries to enrich a chapter with figures.
CURATION = {}


def section_id(idx, title):
    t = title.strip()
    m = re.search(r"[A-Za-z][\w+/&-]*", t)   # first latin token → readable slug
    if m:
        return f"ch{idx}-" + re.sub(r"[^\w]+", "", m.group(0)).lower()[:16]
    return f"ch{idx}"


def split_sections(md_text):
    lines = md_text.splitlines()
    page_title = "תרגול הנדסת תוכנה"
    for ln in lines:
        if ln.startswith("# ") and not ln.startswith("## "):
            page_title = ln[2:].strip(); break
    sections = []; cur_title, cur_buf, preamble = None, [], []
    seen_h1 = False
    for ln in lines:
        if ln.startswith("# ") and not ln.startswith("## "):
            seen_h1 = True; continue
        if ln.startswith("## "):
            if cur_title is not None:
                sections.append((cur_title, "\n".join(cur_buf)))
            cur_title = ln[3:].strip(); cur_buf = []
        elif cur_title is None:
            if seen_h1: preamble.append(ln)
        else:
            cur_buf.append(ln)
    if cur_title is not None:
        sections.append((cur_title, "\n".join(cur_buf)))
    preamble_md = "\n".join(preamble).strip()
    out = []
    for i, (title, body) in enumerate(sections):
        sid = section_id(i, title)
        body = body.strip()
        if i == 0 and preamble_md:
            body = preamble_md + "\n\n" + body
        out.append((sid, title, body))
    return page_title, out


_LIST_RE = re.compile(r"^(\s*)([-*+]|\d+\.)\s+")

def normalize_lists(md):
    """Insert a blank line before a list that directly follows a text line."""
    out = []
    for ln in md.split("\n"):
        if _LIST_RE.match(ln):
            prev = out[-1] if out else ""
            p = prev.strip()
            if p and not _LIST_RE.match(prev) and not p.startswith("#") and not p.startswith("|"):
                out.append("")
        out.append(ln)
    return "\n".join(out)


def figures_html(sid):
    items = CURATION.get(sid, [])
    if not items:
        return ""
    figs = []
    for out_name, caption in items:
        cap = html.escape(caption)
        figs.append(
            f'<figure class="learn-fig"><img loading="lazy" src="images/{out_name}" '
            f'alt="{cap}"><figcaption>{cap}</figcaption></figure>')
    return '<div class="learn-figs">' + "".join(figs) + "</div>"


def main():
    with open(SUMMARY, encoding="utf-8") as f:
        md_text = f.read()
    page_title, sections = split_sections(md_text)
    md = markdown.Markdown(extensions=["tables", "fenced_code", "sane_lists", "attr_list"])
    learn = []
    for sid, title, body in sections:
        md.reset()
        learn.append({"id": sid, "title": title,
                      "html": md.convert(normalize_lists(body)) + figures_html(sid)})
    meta = {"generated": datetime.date.today().isoformat(), "chapters": len(learn)}
    payload = ("/* AUTO-GENERATED by tools/build_learn.py — do not edit by hand. */\n"
               "window.LEARN = " + json.dumps(learn, ensure_ascii=False) + ";\n"
               "window.LEARN_META = " + json.dumps(meta, ensure_ascii=False) + ";\n")
    with open(OUT_JS, "w", encoding="utf-8") as f:
        f.write(payload)
    print(f"page title : {page_title}")
    print(f"sections   : {len(learn)} -> {[s['id'] for s in learn]}")
    print(f"wrote      : {OUT_JS}")


if __name__ == "__main__":
    main()
